### ISSUE TITLE
idea: ability to select terminal with the matching tab name

### ISSUE THREAD

**Issue by umputun** [romaindalichamp/TerminalTabTailor#8]
Thank you for the plugin. One improvement that would greatly enhance its usefulness is the ability to open an existing tab with a matching title instead of opening a new one. This should probably be an optional feature. However, I'm unsure if this is feasible with the APIs JetBrains provides for plugins.

**Comment by romaindalichamp** [comment]
Hi umputun,

Thank you for your suggestion, it sounds like a nice feature to add. This is not provided directly by the API, but i have an idea.

Romain

**Comment by romaindalichamp** [comment]
Hey umputun,

The more I learn about IntelliJ's SDK and code, the more I see opportunities to improve. I've introduced this feature on an experimental basis for now. 

Basically, it checks if a terminal name already exists and cancels the creation of a new one if it does. This method seems to work "okay" in the latest version, 1.2.0, and I plan to make it more robust in future updates. 

The code for the other issue has been merged into the master branch and if you want the new version including the fix before it's official release, you can download the version 1.2.0 as a Jar here: https://plugins.jetbrains.com/plugin/23903-terminal-tab-tailor/versions/in%20review

To install, you can copy/paste the downloaded Jar to the Plugins directory following the instructions here (and remove the previous version): https://www.jetbrains.com/help/idea/directories-used-by-the-ide-to-store-settings-caches-plugins-and-logs.html#plugins-directory

Let me know how it works for you.

Romain

**Comment by romaindalichamp** [comment]
Hey umputun, i wanted to let you know, the fonctionnality is now fully implemented and stable :).
Last version 1.3.1 will be available on market in few days, with the new features.

Please let me know if you enjoy it !

Romain

--
If you want the new version including the fix before it's official release, you can download the version 1.3.1 as a Jar here: https://plugins.jetbrains.com/plugin/23903-terminal-tab-tailor/versions/in%20review

To install, you can copy/paste the downloaded Jar to the Plugins directory following the instructions here (and remove the previous version): https://www.jetbrains.com/help/idea/directories-used-by-the-ide-to-store-settings-caches-plugins-and-logs.html#plugins-directory

**Comment by umputun** [comment]
Thank you a lot. I just updated to 1.3.2, turned on the match options, and everything seems to work nicely!
